### ISSUE TITLE
ProfileCard bio not readable

### ISSUE THREAD

**Issue by rhnvrm** [dubstrike/twitter-dark-mode#12]
ProfileCard-bio u-dir is not readable. To replicate click on a hashtag (eg. https://twitter.com/hashtag/VineetJainSharamKaro?src=tren) and scrolldown.

Have attached the screenshot below. 

![twitter com-hashtag-vineetjainsharamkaro-src tren](https://cloud.githubusercontent.com/assets/952036/23831304/73f506e8-0744-11e7-893d-253e7e008e55.png)

![screenshot from 2017-03-12 16-55-52](https://cloud.githubusercontent.com/assets/952036/23831327/ca7ac49e-0744-11e7-94b7-9425501c2f02.png)

**Comment by pugson** [comment]
@rhnvrm Fixed. Thanks for reporting it!

**Comment by rhnvrm** [comment]
Thanks! (y)
