### ISSUE TITLE
Share intent needs styles

### ISSUE THREAD

**Issue by rhnvrm** [dubstrike/twitter-dark-mode#13]
![screenshot from 2017-03-12 21-48-12](https://cloud.githubusercontent.com/assets/952036/23833558/cb990fb0-076d-11e7-8d4a-b167976c0fbb.png)

To replicate:

https://twitter.com/intent/tweet?url=https%3A//youtu.be/SMKeWTVYBUo&text=%22Linux%20Sucks...%20For%20the%20Last%20Time%22%20-%202017&via=YouTube&related=YouTube,YouTubeTrends,YTCreators

**Comment by pugson** [comment]
@rhnvrm Fixed it. Cheers!

**Comment by rhnvrm** [comment]
@dubstrike Thanks!
