### ISSUE TITLE
Readability of User Dropdown on Hover is low

### ISSUE THREAD

**Issue by rhnvrm** [dubstrike/twitter-dark-mode#14]
Sample:

![screenshot from 2017-03-13 22-38-45](https://cloud.githubusercontent.com/assets/952036/23866128/dee89448-083d-11e7-807b-accbee4a6ad9.png)

To replicate:

Hover on items in dropdown after clicking user profile photo in nav bar.

**Comment by pugson** [comment]
Cheers!

**Comment by rhnvrm** [comment]
@dubstrike Thanks!
