### ISSUE TITLE
Edit Profile

### ISSUE THREAD

**Issue by rhnvrm** [dubstrike/twitter-dark-mode#15]
To replicate:

Goto your profile while logged in and click Edit Profile button.

Screenshot:

![screenshot from 2017-03-14 00-51-01](https://cloud.githubusercontent.com/assets/952036/23871459/7ed023ec-0850-11e7-8b02-8addd5c5b4eb.png)

**Comment by pugson** [comment]
@rhnvrm Good catch. Thanks!
Fixed in https://github.com/dubstrike/twitter-dark-mode/commit/107c8184fd6216744f04c5f68fe6f9538bdbfbb8

**Comment by rhnvrm** [comment]
@dubstrike great! Thanks
