### ISSUE TITLE
Fix Stylish URL regular expression

### ISSUE THREAD

**Issue by elamperti** [dubstrike/twitter-dark-mode#27]
**Problem**
As it is now, Stylish is using this regex: `^(?!.*tweetdeck\.twitter).*(.*twitter\.com.*)` :x: 

This arises problems in cases where it shouldn't be matching:
  * https://github.com/?utm_source=twitter.com
  * https://blog.twitter.com/

**Solution**
It could be fixed by replacing it by this new regex: `^https?:\/\/twitter\.com\/.*` :white_check_mark: 
(which is also a bit more elegant! :bowtie: )

Tested with [this regex101 demo](https://regex101.com/r/6608g5/2) and manually in my browser's Stylish

---

Also line 1 of the CSS should be:

    @-moz-document regexp('^https?:\/\/twitter\.com\/.*') {

(this CSS change won't have effect if it's being manually changed/overriden at Stylish)

**Comment by pugson** [comment]
I've used a regex before but it broke compatibility with TamperMonkey and similar extensions. Check out [this thread on UserStyles](https://forum.userstyles.org/discussion/54668/x). If you find a way to have it working properly with Stylish and TamperMonkey, let me know!

I'm using a `url-prefix` at the moment:
https://github.com/dubstrike/twitter-dark-mode/blob/master/darkmode.scss#L1

**Comment by elamperti** [comment]
The match pattern was updated after the changes you made today for #28, now Stylish is targeting just the correct domains without using regular expressions, so I'll consider this solved :slightly_smiling_face: Thank you!

**Comment by pugson** [comment]
Actually it was [updated over 2 weeks ago](https://github.com/dubstrike/twitter-dark-mode/commit/971171667e53b81f388dfcf3210204f826485a90). Do you have auto-updates enabled in Stylish?

**Comment by elamperti** [comment]
That would explain why I though it was being overriden! :man_facepalming: I'll turn auto-updates on too :grin:

**Comment by pugson** [comment]
@elamperti Cheers!
