### ISSUE TITLE
Text is black

### ISSUE THREAD

**Issue by MetroidCatcher** [dubstrike/twitter-dark-mode#30]
So, i found 2 places where this happens:

1. If a user hasn't tweeted anything. Twitter only displays this "@-username hasn't Tweeted" and this text is black.
2. If a account is suspended.

See attachments. (Hard to read, btw)
![firefox_2017-04-18_10-28-38](https://cloud.githubusercontent.com/assets/16920375/25121508/76bab8fc-2411-11e7-994a-5fcf6454fd78.jpg)
![firefox_2017-04-18_10-29-07](https://cloud.githubusercontent.com/assets/16920375/25121522/80601b9a-2411-11e7-8a79-e2882819758a.jpg)

**Comment by pugson** [comment]
Can you send me the link to a suspended account?

**Comment by MetroidCatcher** [comment]
Every suspended account will be redirected to [this](https://twitter.com/account/suspended).

**Comment by pugson** [comment]
Both issues have been fixed. Make sure you're on the latest version if you're using UserStyles.
Thanks for letting me know!
