### ISSUE TITLE
If a user is in no lists, there's white background also white text

### ISSUE THREAD

**Issue by MetroidCatcher** [dubstrike/twitter-dark-mode#31]
Just the title explains why. 
![firefox_2017-04-23_10-55-06](https://cloud.githubusercontent.com/assets/16920375/25312196/af089c2a-2802-11e7-9560-8e6d5c360ffc.jpg)
![firefox_2017-04-23_10-55-16](https://cloud.githubusercontent.com/assets/16920375/25312197/b479fa50-2802-11e7-8bc6-b6311f8c42bb.jpg)

**Comment by MetroidCatcher** [comment]
Also the same if a user isn't listed yet.
![firefox_2017-04-23_10-57-40](https://cloud.githubusercontent.com/assets/16920375/25312210/fd0a45f4-2802-11e7-958f-0b80101ee6c4.jpg)
![firefox_2017-04-23_10-57-50](https://cloud.githubusercontent.com/assets/16920375/25312211/00a50474-2803-11e7-84bf-3c84afb307f2.jpg)

**Comment by pugson** [comment]
@Kn0p3XX Just pushed an update. Let me know if this issue was fixed.

**Comment by MetroidCatcher** [comment]
It's fixed, thank you.
