### ISSUE TITLE
Twitter recent design changes

### ISSUE THREAD

**Issue by MetroidCatcher** [dubstrike/twitter-dark-mode#39]
I list everything here, that seems weird and/or odd.

"Your Tweet activity"-text is black (Only viewable on your own profile)
"[country-name] Trends"-text (especially on your profile) is dark.
If you're clicking on "Following" and/or "Followers" the bio text in the small boxes are dark.
The box where the "Subscribe" button is (on a list) seems odd. (Here's a random list: https://twitter.com/Twitter/lists/moments )

**Comment by pugson** [comment]
[Just pushed an update](https://userstyles.org/styles/135366/twitter-dark-mode-2017).

Are these issues resolved or is there something else being unstyled still?

**Comment by MetroidCatcher** [comment]
Ah, yes. If i firing a search up. Text "Search filters" is untouched, i overlooked that.

**Comment by MetroidCatcher** [comment]
Also the Drop-Down menus are odd (I almost forgot that again)

**Comment by pugson** [comment]
@Kn0p3XX Which dropdown menus? Would love a screenshot.

**Comment by MetroidCatcher** [comment]
The drop down menus under "Search filters", those are hidden, but it seems fixed now. (All 3 are okay)
![firefox_2017-06-16_19-44-15](https://user-images.githubusercontent.com/16920375/27238149-1d7226ec-52cc-11e7-805b-5597a7b7b5aa.jpg)
