### ISSUE TITLE
Highlight new notifications

### ISSUE THREAD

**Issue by ghost** [dubstrike/twitter-dark-mode#44]
at the moment there's no distinction between new & read notifications, which makes it hard to tell whats new when you have a lot of them ＿ﾉ乙(､ﾝ､)_

i've personally fixed it w this
`li.stream-item.highlighted::before {
    content: "\25CF";
    font-size: 14px;
    left: 5px;
    position: absolute;
    top: 1px;
    color:#1c9dec;
}`

but the way twitter normally does it is by changing the background colour? i couldnt get that to work but im sure you'd kno how. anyway i lov this skin thank u for making it ✌✌

**Comment by pugson** [comment]
@harrie5 Thanks for letting me know. I forgot this existed!

Update to the latest version of the theme, I just pushed this change.
