### ISSUE TITLE
Profile Button Hover messed up

### ISSUE THREAD

**Issue by EthanC** [dubstrike/twitter-dark-mode#48]
![image](https://user-images.githubusercontent.com/16727756/27513711-adf523ac-5936-11e7-9412-5dc91945f118.png)

**Comment by pugson** [comment]
Already fixed with https://github.com/dubstrike/twitter-dark-mode/commit/28c29e27b4140a13f2910fdbb279823821c92a26

Make sure you have the latest version of the theme running.
