### ISSUE TITLE
Create Moment Button Hover messed up

### ISSUE THREAD

**Issue by EthanC** [dubstrike/twitter-dark-mode#51]
![image](https://user-images.githubusercontent.com/16727756/27518982-23582dae-59b1-11e7-82d0-dca24579ceeb.png)

**Comment by pugson** [comment]
I don't have moments on my account. Did the latest changes fix this?

**Comment by EthanC** [comment]
It is now Blue, yes. 
![image](https://user-images.githubusercontent.com/16727756/27615056-30ca357a-5b6b-11e7-903d-4deb977ec142.png)

**Comment by pugson** [comment]
Cool — thanks for confirming!
