### ISSUE TITLE
Twitter Login Dialog Light Colored Border

### ISSUE THREAD

**Issue by EthanC** [dubstrike/twitter-dark-mode#55]
![image](https://user-images.githubusercontent.com/16727756/27519029-be4802e4-59b1-11e7-9f6e-7b7031ecdbaa.png)

**Comment by pugson** [comment]
How do I trigger this modal?

**Comment by EthanC** [comment]
Log out, go to [this page](https://twitter.com/), click Login button on the top-right corner.

**Comment by pugson** [comment]
I guess you have a different logged out page than me.

![img](http://share.wojtek.im/dHA8e+)

**Comment by EthanC** [comment]
Class for it is `.LoginDialog .LoginDialog-footer` It currently has `border-color: #e6ecf0;`

**Comment by pugson** [comment]
Dropping support. Please use the native dark mode for Twitter.
