### ISSUE TITLE
Moments Profile View messed up

### ISSUE THREAD

**Issue by EthanC** [dubstrike/twitter-dark-mode#59]
![image](https://user-images.githubusercontent.com/16727756/27887842-770ddbf2-61a8-11e7-95b4-24d7eb71a0f3.png)

**Comment by pugson** [comment]
Fine on my end. Are you on the latest version of the style?

![img](http://share.wojtek.im/l73cXl+)

**Comment by pugson** [comment]
Never mind, it only shows up on Moments with `Draft` status.
