### ISSUE TITLE
Poll Card Hover messed up

### ISSUE THREAD

**Issue by EthanC** [dubstrike/twitter-dark-mode#70]
![image](https://user-images.githubusercontent.com/16727756/27998609-8146965e-64d7-11e7-9b91-86168c435012.png)

**Comment by DylanPlemmons** [comment]
Polls are in an iframe so the hover on the tweet doesn't effect the poll style. Sass might be able to fix this but I don't think Stylish supports sass. But I'll try to find a way to fix this and I'll also fix the button.

**Comment by pugson** [comment]
@DylanPlemmons Stylish doesn't support Sass, but the source of this theme is using Sass (scss syntax) and compiles to CSS.
