### ISSUE TITLE
Suggestion: Revert Dark-Blue Color Override

### ISSUE THREAD

**Issue by EthanC** [dubstrike/twitter-dark-mode#74]
Recent-ish update began to override user profile colors with the dark-blue from this theme. I personally disagree with this change and feel that it limits user customization, not a good UX decision. I'm aware that the dark-blue blends better with the stylish theme, and that some Twitter colors may clash, but that is entirely in control of the user and not something this theme should override.

Stylish supports _modular_-esque themes allow you to give the user dropdowns that'll modify their theme locally, you could give the users multiple color choices that flow well with this theme as well. Or even just have the default set to dark-blue and allow users to enable custom profile colors if they wish.

Would love any healthy discussion on this change!

**Comment by pugson** [comment]
The problem with that is when you visit someone else's profile, you're automatically inheriting their profile color. There's no way to prevent that without overriding all custom colors.

How about defaulting to the dark blue and allowing users to disable the override with the dropdown in Stylish?

_Edit: Hah, just read it again and it's also what you're suggesting._

**Comment by EthanC** [comment]
I think that's a good middle ground :)

**Comment by pugson** [comment]
Twitter removed custom colors from profiles.
