### ISSUE TITLE
Leftover Lightmode on Photos Search Results Page

### ISSUE THREAD

**Issue by EthanC** [dubstrike/twitter-dark-mode#81]
## Is something unstyled or looking weird?
- Bottom Bar of the Photos Search Results Page
- Class: `.stream-container .AdaptiveStreamGridImage .grid-tweet-actions-container`

## URL of where this happens or steps to reproduce
- https://twitter.com/search?f=images&q=web%20design&src=typd (Hover an image)

## Screenshots
![image](https://user-images.githubusercontent.com/16727756/28245547-31d35218-69cf-11e7-9f78-92749d9558ad.png)

**Comment by pugson** [comment]
Never knew this even existed. Thanks!
