### ISSUE TITLE
Leftover Lightmode on Search Filters Dropdown

### ISSUE THREAD

**Issue by EthanC** [dubstrike/twitter-dark-mode#83]
## Is something unstyled or looking weird?
- Dropdown Menu Selections on the Search Filters

## URL of where this happens or steps to reproduce
- https://twitter.com/search?f=tweets&q=web%20askndaksdnkasnkd&src=typd
Select 'Search Filters' on the left side modal

## Screenshots
![image](https://user-images.githubusercontent.com/16727756/28245570-c2f129dc-69cf-11e7-923a-54a6782cf434.png)

**Comment by pugson** [comment]
Should be fixed along with https://github.com/dubstrike/twitter-dark-mode/issues/84
