### ISSUE TITLE
Image preview is cutting of the bottom (eg. no transparency)

### ISSUE THREAD

**Issue by MetroidCatcher** [dubstrike/twitter-dark-mode#91]
## Is something unstyled or looking weird?
The image preview is looking weird (Click on image to see it, with and without style change)

## URL of where this happens or steps to reproduce
https://twitter.com/MetroidDatabase/status/888748209346154497
Basically on every image on Twitter Web

## Screenshots
Original style
![firefox_2017-07-22_22-24-07](https://user-images.githubusercontent.com/16920375/28494361-5cab979a-6f2c-11e7-80fb-3c51bb170620.jpg)

Twitter Dark Mode style
![firefox_2017-07-22_22-18-37](https://user-images.githubusercontent.com/16920375/28494362-6568114c-6f2c-11e7-9887-95c26f243f1c.jpg)

**Comment by pugson** [comment]
I'm currently away until Friday. Would love a PR for this, so I can update the style.

**Comment by PandorasFox** [comment]
Depending on how hacky you want it to be, the following will work:

```
.stream-item-footer {
  background-color: #212c3b;
}
.tweet.js-stream-tweet.has-cards.Tweet--invertedColors.has-content {
    background-color: rgba(0,0,0,0) !important;
}
.Gallery-content:hover .tweet.js-stream-tweet.has-cards.Tweet--invertedColors.has-content {
    background-color: #212c3b !important;
}
```

Alternatively - I _think_ that if we pull the `body .GalleryTweet .tweet` out of [here](https://github.com/dubstrike/twitter-dark-mode/blob/master/darkmode.scss#L173) and put it in its own declaration for the same color (but without the !impotant), it'll work fine. (I'm not entirely sure that the !important there is needed for all those specifiers, so moving some of them out into a non-important declaration may make stuff easier?)

(I don't know exactly what in there needs the !important, but from my initial pokings, it doesn't seem like _any_ of them do?)

**Comment by pugson** [comment]
@chrjguill Got it, thanks!
