### ISSUE TITLE
Mobile Twitter partially not colored; tweets are dark

### ISSUE THREAD

**Issue by MetroidCatcher** [dubstrike/twitter-dark-mode#94]
## Is something unstyled or looking weird?
Mobile Twitter header white on the edges, main tweet w/ replies having dark colors

## URL of where this happens or steps to reproduce
https://mobile.twitter.com/MetroidDatabase/status/896719724997988352
Bascially everywhere on mobile Twitter.

## Screenshots
![screenshot-2017-8-14 metroid database auf twitter quiz of the week in super metroid the roars for enemies like crocomir](https://user-images.githubusercontent.com/16920375/29273603-2ed85caa-8105-11e7-89a4-64958876d61f.png)

**Comment by MetroidCatcher** [comment]
Oh, don't wonder, the header is in the middle of the picture, i don't know why, that isn't a bug from Twitter, just you know.

**Comment by pugson** [comment]
Thanks for reminding me! There were more issues on mobile.twitter.com that I fixed as well.
